// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
main()
{
	assert(isdefined(self));
	wait 0;
	if (isdefined(self))
		self delete();
}
