// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
InitStructs()
{
	level.struct = [];
}

CreateStruct()
{
	struct = spawnstruct();
	level.struct[level.struct.size] = struct;
	return struct;
}
