// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	character\character_mp_sas_urban_recon::main();
}

precache()
{
	character\character_mp_sas_urban_recon::precache();
}
