// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_sas_urban_assault");
	self setViewmodel("viewhands_black_kit");
	self.voice = "british";
}

precache()
{
	precacheModel("body_mp_sas_urban_assault");
	precacheModel("viewhands_black_kit");
}
